"""Generate the corpus schema from the manifest (`BUNDLE.md` §2, `CLAUDE.md` §7).

> Schema is generated from the manifest, not hardcoded. Embedding dimension is a variable
> because the embedder is a plugin.

Vera reached the same conclusion from the other side and wrote it down in
`migrations/README.md`, after deleting a schema file that had drifted from the database:

    `0001_init.sql` was deleted. It described a system that was never built —
    halfvec(4096), a domains table, chunks partitioned by HASH(cluster_id), NOT NULL
    provenance. The live corpus is halfvec(1024), has no domains table, is not
    partitioned, and has nullable source_url. Keeping a schema file that contradicts the
    database in every particular is worse than having none: it is the first thing someone
    reads.

That is the argument for generating it. A hand-maintained schema and a built corpus drift
apart silently, and the schema is what a reader trusts first. Generated from the manifest,
the two cannot disagree — a wrong schema means a wrong manifest, which means a bundle that
fails its own preflight.

! `ravel load` applies this; nothing applies it automatically. What a corpus needs
*after* ingestion — the provenance trigger, an optional RUM index — stays in hand-applied
migrations, because those are operational choices, not properties of the data.
"""

from __future__ import annotations

from bundle.manifest import BundleManifest

__all__ = ["render_indexes", "render_schema"]

_HEADER = """\
-- Generated by Ravel from the bundle manifest. Do not edit.
--
-- corpus     : {corpus_id}
-- manifest   : {manifest_sha}
-- dense      : {dense_model} @ {dense_version} · {dense_dim}d · {pooling} · {padding} pad
-- sparse     : {sparse_desc}
-- chunker    : {chunker}
-- generated  : {created_at}
--
-- ! Every dimension below came from the manifest. A bundle and a database are married
-- by dimension (EMBEDDING.md §2): loading a {dense_dim}-dim bundle into a database built
-- for another width fails at COPY, which is the right place to fail.

CREATE EXTENSION IF NOT EXISTS vector;
"""

_CORPUS_META = """
-- ---------------------------------------------------------------------------
-- corpus_meta · the recipe, recorded with the data it produced.
--
-- The engine validates a query embedding against THIS ROW, not against a constant
-- compiled into its binary. That is what makes the consistency rule enforceable rather
-- than aspirational.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS corpus_meta (
    id                  TEXT PRIMARY KEY,
    run_id              TEXT        NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Dense side · every field that changes the vector space.
    dense_model         TEXT    NOT NULL,
    dense_model_version TEXT    NOT NULL,
    dense_dim           INTEGER NOT NULL,
    dense_pooling       TEXT    NOT NULL,
    dense_normalize     BOOLEAN NOT NULL,
    dense_dtype         TEXT    NOT NULL,

    -- ! Not present in the schema this was modelled on, and its absence is the
    -- defect in ABSORPTION.md §11. Under last-token pooling the padding side decides
    -- which token is read; a corpus built with one and queried with the other pools a
    -- PAD position and returns well-formed nonsense.
    dense_padding_side  TEXT    NOT NULL,

    -- ! Three columns, not one. A single `dense_instruction TEXT` cannot say whether the
    -- instruction is a prefix or a chat system turn, cannot carry different document and
    -- query strings, and records "never applied" as NULL — indistinguishable from a
    -- model that legitimately takes none.
    dense_instruction_style TEXT NOT NULL,
    dense_doc_instruction   TEXT NOT NULL DEFAULT '',
    dense_query_instruction TEXT NOT NULL DEFAULT '',

    -- Sparse side · the vocabulary is part of the recipe. Without it a query cannot be
    -- projected into the space at all.
    sparse_scheme       TEXT,
    sparse_dim          INTEGER,
    sparse_k1           REAL,
    sparse_b            REAL,
    sparse_vocab_sha256 TEXT,
    sparse_fit_docs     INTEGER,

    chunker             TEXT NOT NULL DEFAULT '',
    chunker_version     TEXT NOT NULL DEFAULT '',
    profile_ref         TEXT NOT NULL DEFAULT '',

    -- ! The profile's `scoring:` block, resolved, so the ENGINE stops carrying its own
    -- copy. Vera's `engine::factors` compiled in ten UNDANG-UNDANG/PERATURAN literals,
    -- the strings LAMPIRAN/PENJELASAN/PASAL and 25 Indonesian function words -- the same
    -- tables this profile already declares. Two copies in two repositories that must
    -- agree are two copies that will eventually disagree, and only one of them can be
    -- right for a corpus that is not Indonesian regulation.
    --
    -- Same rule as `dense_pooling` and `sparse_vocab_sha256`: on a corpus these tables do
    -- not describe, `authority` and `structural` evaluate neutrally for every row and the
    -- operator's weights do nothing AT ALL -- silently. Recording the vocabulary beside
    -- the data is what lets the engine notice.
    --
    -- JSONB, not columns: the shape is a profile's to define and the engine's to read,
    -- and a new factor family must not be a migration on a table Vera only reads.
    -- NULL means a corpus loaded before this existed; the engine falls back and says so.
    scoring_vocabulary  JSONB,
    text_search_config  TEXT NOT NULL,
    source_manifest_sha256 TEXT NOT NULL,
    manifest_sha256     TEXT NOT NULL,
    notes               TEXT
);
"""

_CHUNKS = """
-- ---------------------------------------------------------------------------
-- chunks · immutable. Enrichment lives in sidecar tables (CLAUDE.md §5.4).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chunks (
    id                  TEXT PRIMARY KEY,
    corpus_id           TEXT NOT NULL REFERENCES corpus_meta(id),

    regulation_type     TEXT,
    enacting_body       TEXT,
    regulation_number   TEXT,
    year                INTEGER,
    about               TEXT,
    chapter             TEXT,
    article             TEXT,
    identifier          TEXT,
    chunk_no            INTEGER,

    body                TEXT NOT NULL,

    -- ! Provenance and lineage, as hard columns. These are in the chunk parquet and were
    -- NOT in the schema this was modelled on, because the pipeline that built that corpus
    -- never carried them — which is the same reason all 748,558 of its rows have no
    -- source_url (ABSORPTION.md §3). `CLAUDE.md` §5.3 calls provenance the product, and a
    -- column that exists in the bundle and not in the database is a product that does not
    -- arrive. Ravel writes and Vera reads, so the wider schema is the one that wins.
    doc_id              TEXT NOT NULL DEFAULT '',
    token_count         INTEGER,
    source_sha256       TEXT NOT NULL DEFAULT '',
    locator_page        INTEGER,
    locator_section     TEXT,
    heading_path        TEXT,

    chunker             TEXT NOT NULL DEFAULT '',
    chunker_version     TEXT NOT NULL DEFAULT '',
    config_hash         TEXT NOT NULL DEFAULT '',
    profile             TEXT,

    {source_url_column}
    source_title        TEXT NOT NULL,

    -- Honest flags, set at ingest, never inferred at query time.
    truncated_at_source BOOLEAN NOT NULL DEFAULT FALSE,
    indexable           BOOLEAN NOT NULL DEFAULT TRUE,

    -- ! How this chunk's text was obtained, and whether its text layer was trusted.
    -- ABSORPTION.md §18.3: an extraction setting nobody recorded is a setting nobody can
    -- review. With these, "how much of this corpus came from OCR" is a query.
    extractor           TEXT NOT NULL DEFAULT '',
    text_layer          TEXT NOT NULL DEFAULT '',

    cluster_id          INTEGER,

    dense               halfvec({dense_dim}){sparse_column}

    -- ! '{text_search_config}' — set from the manifest, not assumed.
    tsv tsvector GENERATED ALWAYS AS (to_tsvector('{text_search_config}', body)) STORED,

    ingested_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""

_INDEXES = """
-- ---------------------------------------------------------------------------
-- Indexes · applied AFTER the bulk load, never before (BUNDLE.md §6).
--
-- ! Index maintenance during COPY is the classic way to turn a 20-minute load into a
-- six-hour one: every row insert also rewrites GIN posting lists that a single build pass
-- would have written once, sorted. They are emitted separately from the table DDL so the
-- load procedure cannot accidentally apply them in the wrong order — the ordering is
-- structural rather than remembered.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS chunks_tsv_idx       ON chunks USING GIN (tsv);
CREATE INDEX IF NOT EXISTS chunks_cluster_idx   ON chunks (cluster_id);
CREATE INDEX IF NOT EXISTS chunks_indexable_idx ON chunks (indexable) WHERE indexable;

-- The exact-identifier path must never depend on routing, so it gets its own btree and
-- searches globally.
CREATE INDEX IF NOT EXISTS chunks_identifier_idx
    ON chunks (regulation_type, regulation_number, year);

ANALYZE chunks;
"""

_PROGRESS = """
-- ---------------------------------------------------------------------------
-- ingest_progress · resumability is a table, not a flag.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ingest_progress (
    chunk_id    TEXT PRIMARY KEY,
    run_id      TEXT NOT NULL,
    corpus_id   TEXT NOT NULL,
    stage       TEXT NOT NULL,           -- loaded | dense | sparse | done
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ingest_progress_run_idx ON ingest_progress (run_id, stage);
"""


def render_indexes(manifest: BundleManifest) -> str:
    """The index DDL, separated so the loader can apply it after `COPY`.

    Takes the manifest rather than nothing because the index set is a property of the
    corpus: a bundle with no sparse arm needs no sparse index, and a future variant that
    adds one must not silently inherit the last variant's indexes.
    """
    _ = manifest
    return _INDEXES


def render_schema(
    manifest: BundleManifest,
    *,
    provenance_complete: bool = True,
    with_indexes: bool = True,
) -> str:
    """The DDL for this bundle, with every dimension taken from the manifest.

    `provenance_complete` decides whether `source_url` is `NOT NULL`. It is a parameter
    rather than a constant because the incumbent corpus cannot satisfy it and is still
    worth loading as a scored baseline — flagged, not dressed up (`ABSORPTION.md` §3).
    Defaulting it to True means a corpus is provenance-complete unless somebody says
    otherwise, which is the direction the mistake should point.
    """
    dense = manifest.dense
    sparse = manifest.sparse

    source_url = (
        "source_url          TEXT NOT NULL,"
        if provenance_complete
        else (
            "-- ! Nullable: this corpus has chunks with no source_url, and inventing one\n"
            "    -- is forbidden (CLAUDE.md §7.4). Results carrying NULL must be reported as\n"
            "    -- provenance-incomplete rather than dressed up as verifiable.\n"
            "    source_url          TEXT,"
        )
    )

    sparse_column = f",\n    sparse              sparsevec({sparse.dim})," if sparse else ","
    sparse_desc = (
        f"{sparse.scheme} · {sparse.dim}d · k1={sparse.k1} b={sparse.b} · "
        f"vocab fitted over {sparse.fit_docs:,} docs"
        if sparse
        else "none declared"
    )

    header = _HEADER.format(
        corpus_id=manifest.corpus_id,
        manifest_sha=manifest.fingerprint(),
        dense_model=dense.model,
        dense_version=dense.model_version,
        dense_dim=dense.dim,
        pooling=dense.pooling,
        padding=dense.padding_side,
        sparse_desc=sparse_desc,
        chunker=(
            f"{manifest.chunker}@{manifest.chunker_version}" if manifest.chunker else "none"
        ),
        created_at=manifest.created_at,
    )
    chunks = _CHUNKS.format(
        dense_dim=dense.dim,
        sparse_column=sparse_column,
        source_url_column=source_url,
        text_search_config=manifest.text_search_config,
    )
    ddl = header + _CORPUS_META + chunks + _PROGRESS
    return ddl + _INDEXES if with_indexes else ddl
